[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_blog = "3LAQqBgaMeYuBZ9PXKm9LJ3KaV3GR2JKtRbv1gdUfd1T"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/luka/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
