[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_blog = "35AsEX1LkmsL96t7X91JYiw7cv7TtgEqybMvFwv5qpfn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/luka/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
